% population_decoding_SVM.m - This code is designed to use a support vector
% machine to decode odor stimulus identity on the basis of simultaneously
% recorded neurons from a particular brain region of one mouse
%
%   Inputs:
%       mouseLabel - standardized label that identifies a particular mouse
% 
%       [AK###]_spikes_grouped_by_odor_trial.mat - file containing population 
%       activity for all odorant trials for a single animal.
%           Dimension 1 - odorant #
%           Dimension 2 - trial #
%           Dimension 3 - unit #
%           Dimension 4 - binary spike (denoting presence(1)/absence(0) of 
%                           a spike at each sample points spanning the trial)
%           (Source: this data structure is automatically generated by the 
%           "align_sorted_spikes_to_odor_delivery.m" script.)
%
%   Outputs:
%       ...
%
%   Dependencies:
%       ...
%
% Designed by Anna C. Kolstad
% Author contact email: anna_kolstad@urmc.rochester.edu
% Padmanabhan Lab, University of Rochester School of Medicine
% PI contact email: krishnan_padmanabhan@urmc.rochester.edu
% Script first created: December 5, 2025 (Version 1.0)
% Script last updated: April 15, 2026
% Version 2.0. 

%% SUMMARY OF DATA

% AK014: had 30 vCA1 units simultaneously recorded -- DONE
% AK025: had 19 vCA1 units simultaneously recorded
% AK024: had 24 dentate gyrus units simultaneously recorded
% AK027: had 46 CA3 units simultaneously recorded -- DONE

%% PART ONE: Load the data
% Specifically, load the population activity from a single animal across '
% all trials of all odorants

clear vars
clc

% Manually specify Mouse ID
mouseLabel = inputdlg('Enter animal ID','User input');

% Manually specify region of interest
regionLabel = inputdlg('Enter region ID (e.g. CA1, CA3, DG)','User input');
if strcmp(string(regionLabel),"CA1")
    region{1} = "vCA1";
    region{2} = "iCA1";
elseif strcmp(string(regionLabel),"CA3")
    region{1} = "vCA3";
    region{2} = "iCA3";
elseif strcmp(string(regionLabel),"DG")
    region{1} = "DG";
    region{2} = "NOT A REGION";
end

% Select base directory from which to navigate data section
baseDir = uigetdir('',"Select base directory for this animal.");

% Load odor labels for this experiment
[file, path] = uigetfile(".mat","Select [AK###]_odors.mat file for " + mouseLabel + ".",baseDir);
tic
disp("Loading odorant names for this experiment...")
load(fullfile(path,file));
toc

% Load odor color variables
[file, path] = uigetfile(".mat","Select odorColors.mat file.", baseDir);
tic
disp("Loading odorant colors and markers...")
load(fullfile(path,file)); % note: took <3 mins
toc
classesSortedbyFcnGrp = ["limonene" "cumene" "1-octanol" "eugenol" "hexanal" "valeraldehyde" "amyl acetate" "isoamyl acetate" "acetophenone" "valeric acid" "mineral oil" "air"];

% select path for output figures
baseOutputPath = uigetdir(path,"Select base directory in which to save outputs.");
saveFigDir = baseOutputPath;
% make new folder if it does not already exist
if ~exist(saveFigDir,'dir')
    mkdir(saveFigDir);
end

% Load spike variable
[file, path] = uigetfile(".mat","Select [AK###]_spikes_grouped_by_odor_trial.mat file for " + mouseLabel + ".",baseDir);
tic
disp("Loading population activity for all odorant trials...")
load(fullfile(path,file)); % note: took <3 mins
toc



%%

% Get dimensions of dataset
nOdors = size(spikeRaster,1);
nTrialsPerOdor = size(spikeRaster,2);
nUnits = size(spikeRaster,3);

% Convert time stamps into sampling point units
pointsBefore = timeBefore*sampFreq;
pointsDuring = timeDuring*sampFreq;
pointsAfter = timeAfter*sampFreq;

% Get unit to region mapping
getRegion = [];
for iUnit = 1:nUnits
    getRegion = [getRegion; unitInfo.("UNIT" + num2str(iUnit, "%.3d")).info.anatomicAbbrev];
end

% Extract only units from specified region
unitsInRegion = [];
for iUnit = 1:nUnits
    thisRegion = getRegion(iUnit);
    if thisRegion == region{1}
        unitsInRegion = [unitsInRegion iUnit];
    elseif thisRegion == region{2}
        unitsInRegion = [unitsInRegion iUnit];
    end
end
mask = true(1, size(spikeRaster,3));
mask(unitsInRegion) = false;
spikeRaster(:,:,mask,:) = []; % Feb 2026 TO FIX -- RUNNING OUT OF MEMORY HERE AT THIS STEP!!
tic
thisRegionSpikeRaster = spikeRaster;
toc
clear spikeRaster

% For now, we will only analyze odor panel #1 (12 odors total)
nOdors = 12;
thisRegionSpikeRaster = thisRegionSpikeRaster(1:nOdors,:,:,:);
nUnitsThisRegion = size(thisRegionSpikeRaster,3);

clear rowNum region iUnit


%% PART TWO: Generate feature vectors

% Feature vector ideas adapted from Bolding, 2017:
% APPROACH #1 - Binary activation vectors (whether spike count for the unit on this 
% trial was >1SD greater than mean spike count for that unit across all
% blank trials) ** WOULD NEED TO COMPUTE PER-TRIAL RESPONSES

% APPROACH #2 - Total spike counts during a response window (3 seconds) <-- ** TRY THIS APPROACH FIRST

% Trim data to only include during odor delivery period
duringRasters = thisRegionSpikeRaster(:,:,:,pointsBefore:pointsBefore+pointsDuring);

% Sum the total number of spikes during the odor delivery period for each
% trial
spikeCounts = sum(duringRasters,4); % This is the feature vector

% APPROACH #3 - Binned spike counts across a response window (15, 200-ms bins)

%% Organize the input vectors

classesSortedbyNumbering = ["limonene" "cumene" "1-octanol" "eugenol" "hexanal" "valeraldehyde" "acetophenone" "amyl acetate" "valeric acid" "isoamyl acetate" "mineral oil" "air"];
classesSortedbyFcnGrp = ["limonene" "cumene" "1-octanol" "eugenol" "hexanal" "valeraldehyde" "amyl acetate" "isoamyl acetate" "acetophenone" "valeric acid" "mineral oil" "air"];

Xall = [];
Yall = [];
classes = [];
% iterate through odors according to functional group
for iOdor = 1:nOdors
    thisOdorNum = find(strcmp(classesSortedbyFcnGrp(iOdor),classesSortedbyNumbering));
    Xall = [Xall; squeeze(spikeCounts(thisOdorNum,:,:))];
    Yall = [Yall repmat(string(odorIdentities{thisOdorNum}),1,nTrialsPerOdor)];
    classes = [classes string(odorIdentities{thisOdorNum})];
end

% %Run this once to define the color marker pairs for each odorant
%colors = createpastelcolormatrix(nOdors, 0.8, 1);
%markers = 'o+*.xsd^v><p';
%save("odorColors.mat",'colors','markers','classesSortedbyFcnGrp')

%% Visualize the data -- first perform PCA

disp("Visualizing the data using PCA...")

% Perform PCA on population responses
[PCAcoeff, score, latent, tsquared, explained, mu] = pca(Xall);

%% Visualize the data -- Plot PCA in 2D for all odors

figure
gscatter(score(:,1),score(:,2),categorical(Yall,classesSortedbyFcnGrp),colors,markers,'filled')
hold on
title({mouseLabel{1} + ", " + num2str(nUnitsThisRegion) + " " + regionLabel{1} + " units, all trials", "All odors"})
xlabel("PC 1")
ylabel("PC 2")
xLimits = xlim;
yLimits = ylim;
legend('Location','eastoutside')
hold off

saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_PCA_2D_allodors" + ".png")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_PCA_2D_allodors" + ".fig")

figure
for iOdor = 1:nOdors
    subplot(3,4,iOdor)
    indices = strcmp(Yall,classesSortedbyFcnGrp{iOdor});
    gscatter(score(indices,1),score(indices,2),categorical(Yall(1,indices)),colors(iOdor,:),markers(iOdor),'filled');
    xlim(xLimits)
    ylim(yLimits)
    xlabel('PC1')
    ylabel('PC2')
    legend('Location','northoutside')
end
sgtitle({mouseLabel{1} + ", " + nUnitsThisRegion + " " + regionLabel{1} + " units, all trials"})

saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_PCA_2D_eachodor" + ".png")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_PCA_2D_eachodor" + ".fig")

%% Visualize the data -- Plot PCA in 3D for all odors

% Plot neural response to all odors on a single set of axes
figure 
ax(1) = subplot(3,6, [1:3, 7:9]);
for iOdor = 1:nOdors
    indices = find(strcmp(Yall,classesSortedbyFcnGrp{iOdor}));
    if ismember(iOdor,[2 3 4 5])
        scatter3(score(indices,1), score(indices,2), score(indices,3), 60, colors(iOdor,:),markers(iOdor))
    else
        scatter3(score(indices,1), score(indices,2), score(indices,3), 60, colors(iOdor,:),markers(iOdor),'filled')
    end
    hold on
end
grid on
xlabel("PC 1")
ylabel("PC 2")
zlabel("PC 3")
xLimits = xlim;
yLimits = ylim;
zLimits = zlim;
title({mouseLabel{1} + ", " + num2str(nUnitsThisRegion) + " " + regionLabel{1} + " units, all trials", "All odors"})
legend(classesSortedbyFcnGrp,'Location','eastoutside')
hold off

saveas(gcf, saveFigDir + "\" + mouseLabel + "_PCA_3D_allodors" + ".png")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_PCA_3D_allodors" + ".fig")

openPositions = [4:6, 10:12, 13:18];
for iOdor = 1:nOdors
    ax(1+iOdor) = subplot(3,6,openPositions(iOdor));
    indices = strcmp(Yall,classesSortedbyFcnGrp{iOdor});
    if ismember(iOdor,[2 3 4 5])
        scatter3(score(indices,1), score(indices,2), score(indices,3), 60, colors(iOdor,:),markers(iOdor))
    else
        scatter3(score(indices,1), score(indices,2), score(indices,3), 60, colors(iOdor,:),markers(iOdor),'filled')
    end    
    xlim(xLimits)
    ylim(yLimits)
    zlim(zLimits)

    xlabel('PC1')
    ylabel('PC2')
    zlabel('PC3')
    legend(classesSortedbyFcnGrp{iOdor},'Location','northoutside')
end
sgtitle({mouseLabel{1} + ", " + nUnitsThisRegion + " " + regionLabel{1} + " units, all trials"})

hlink = linkprop(ax, {'CameraPosition','CameraTarget','CameraUpVector'});

rotate3d on

saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_PCA_3D_eachodor" + ".png")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_PCA_3D_eachodor" + ".fig")

%% Visualize the data -- next perform NNMF to extract 2 features

disp("Visualizing the data using NNMF...")

% Arrange the feature matrix such that each column represents a
% high-dimensional neural response vector for a single odor trial
A = Xall.'; % n x m; each column contains n non-negative values representing...
% the spike count of each neuron during m odor delivery trials (n = # of
% neurons, m = # of trials)

% Perform non-negative matrix factorization
seed = 1; % define which seed to use for the pseudo random number generator
rng(seed) % for reproducibility
k = 2; % number of features to extract
[W,H] = nnmf(A,k);

% Plot separately by odor identity
figure
gscatter(H(1,:),H(2,:),categorical(Yall,classesSortedbyFcnGrp),colors,markers,'filled')
hold on
title({mouseLabel{1} + ", " + nUnitsThisRegion + " " + regionLabel{1} + " units, all trials", "All odors"})
xlabel("Weight associated with feature 1")
ylabel("Weight associated with feature 2")
xLimits = xlim;
yLimits = ylim;
legend('Location','eastoutside')
hold off

saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_NNMF_2D_allodors" + ".png")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_NNMF_2D_allodors" + ".fig")

% Inidividual subplots for each odor
figure
for iOdor = 1:nOdors
    subplot(3,4,iOdor)
    indices = strcmp(Yall,classesSortedbyFcnGrp{iOdor});
    gscatter(H(1,indices),H(2,indices),categorical(Yall(1,indices)),colors(iOdor,:),markers(iOdor),'filled');
    xlim(xLimits)
    ylim(yLimits)
    xlabel("F1")
    ylabel("F2")
    legend('Location','northoutside')
end
sgtitle("NNMF, " + mouseLabel{1} +", " + regionLabel{1} + " units, all trials")

saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_NNMF_2D_eachodor" + ".png")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_NNMF_2D_eachodor" + ".fig")
%% Visualize the data -- next perform NNMF to extract 3 features

% Arrange the feature matrix such that each column represents a
% high-dimensional neural response vector for a single odor trial
A = Xall.'; % n x m; each column contains n non-negative values representing...
% the spike count of each neuron during m odor delivery trials (n = # of
% neurons, m = # of trials)

% Perform non-negative matrix factorization
seed = 1; % define which seed to use for the pseudo random number generator
rng(seed) % for reproducibility
k = 3; % number of features to extract
[W,H] = nnmf(A,k);

figure 
ax(1) = subplot(3,6, [1:3, 7:9]);
for iOdor = 1:nOdors
    indices = find(strcmp(Yall,classesSortedbyFcnGrp{iOdor}));
    if ismember(iOdor,[2 3 4 5])
        scatter3(H(1,indices),H(2,indices),H(3,indices), 60, colors(iOdor,:),markers(iOdor))
    else
        scatter3(H(1,indices),H(2,indices),H(3,indices), 60, colors(iOdor,:),markers(iOdor),'filled')
    end
    hold on
end
grid on
xlabel("F1")
ylabel("F2")
zlabel("F3")
xLimits = xlim;
yLimits = ylim;
zLimits = zlim;
title({"NNMF, p = 3, " + mouseLabel{1} + ", " + nUnitsThisRegion + " " + regionLabel{1} + " units, all trials", "all odors"})
legend(classesSortedbyFcnGrp,'Location','eastoutside')
hold off

openPositions = [4:6, 10:12, 13:18];
for iOdor = 1:nOdors
    ax(1+iOdor) = subplot(3,6,openPositions(iOdor));
    indices = strcmp(Yall,classesSortedbyFcnGrp{iOdor});
    if ismember(iOdor,[2 3 4 5])
        scatter3(H(1,indices),H(2,indices),H(3,indices), 60, colors(iOdor,:),markers(iOdor))
    else
        scatter3(H(1,indices),H(2,indices),H(3,indices), 60, colors(iOdor,:),markers(iOdor),'filled')
    end  
    xlim(xLimits)
    ylim(yLimits)
    zlim(zLimits)

    xlabel('F1')
    ylabel('F2')
    zlabel('F3')
    legend(classesSortedbyFcnGrp{iOdor},'Location','northoutside')
end
sgtitle("NNMF, p = 3, " + mouseLabel{1} + ", " + nUnitsThisRegion + " " + regionLabel{1} + " units, all trials")

hlink = linkprop(ax, {'CameraPosition','CameraTarget','CameraUpVector'});

rotate3d on

saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_NNMF_3D_eachodor" + ".png")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_NNMF_3D_eachodor" + ".fig")

%% PART THREE: Create training and test data

% To start, let's try just using two classes -- odor 1 and odor 12

% Get two feature vectors
populationResponseAllTrialsOdor1 = squeeze(spikeCounts(1,:,:)); % each row is the population vector response for a single trial
populationResponseAllTrialsOdor12 = squeeze(spikeCounts(12,:,:)); % each row is the population vector response for a single trial

% Bolding 2017 used Leave-One-Out cross validation

% X = feature vector = neural population activity
X = [populationResponseAllTrialsOdor1; populationResponseAllTrialsOdor12];
% Y = odor identity
%Ynum = [1*ones(1,size(populationResponseAllTrialsOdor1,1)) 12*ones(1,size(populationResponseAllTrialsOdor12,1))];
Y = [repmat(odorIdentities(1),1,size(populationResponseAllTrialsOdor1,1)) repmat(odorIdentities(12),1,size(populationResponseAllTrialsOdor12,1))];

% First, practice by training the SVM on the full dataset
SVMModel = fitcsvm(X,Y,"ClassNames",[odorIdentities(1) odorIdentities(12)]);

% Get information on SVM and 
classOrder = SVMModel.ClassNames;

% Visualize model results using first two neuron's responses
sv = SVMModel.SupportVectors;
figure
gscatter(X(:,1),X(:,2),categorical(Y))
hold on
plot(sv(:,1),sv(:,2),'ko','MarkerSize',10)
legend(classOrder{1},classOrder{2},"Support Vector")
title({mouseLabel + " , " + nUnitsThisRegion + " " + regionLabel + " units, all trials","Odor 1 versus Odor 12"})
xlabel("response of neuron 1")
ylabel("response of neuron 2")
hold off

% Try visualizing instead using PCA
% Perform PCA on population responses
[PCAcoeff, score, latent, tsquared, explained, mu] = pca(X);
% Project the SVM results into the same PC space
svCentered = sv - mu; % Center support vectors using PCA mean
svPCA = svCentered * PCAcoeff; % Project centered support vectors into PCA space

figure
gscatter(score(:,1),score(:,2),categorical(Y))
hold on
plot(svPCA(:,1),svPCA(:,2),'ko','MarkerSize',10)
legend(classOrder{1},classOrder{2},"Support Vector")
title({mouseLabel + " , " + nUnitsThisRegion + " " + regionLabel + " units, all trials","Odor 1 versus Odor 12"})
xlabel("PC 1")
ylabel("PC 2")
hold off

% Visualize PCA results in 3 dimensions
figure 
odorClasses = unique(Y);
colors = lines(length(odorClasses));
for i = 1:length(odorClasses)
    idx = find(strcmp(Y,odorClasses{i}));
    scatter3(score(idx,1), score(idx,2), score(idx,3), 60, colors(i,:),'filled')
    hold on
end
plot3(svPCA(:,1),svPCA(:,2),svPCA(:,3),'ko','MarkerSize',10)
%grid on
xlabel("PC 1")
ylabel("PC 2")
zlabel("PC 3")
title({mouseLabel + " , " + nUnitsThisRegion + " " + regionLabel + " units, all trials","Odor 1 versus Odor 12"})
legend(classOrder{1},classOrder{2},"Support Vector")
hold off

%% Now, build the model using a training dataset and use the model to
% predict the odor identity for a test dataset

% Use the first 11 trials as training data
% Leave out the last trial as the test data
trainX = X(1:end-1,:); 
testX = X(end,:);
trainY = Y(1:end-1);
testY = Y(end);

% Build the model
SVMModeltrained = fitcsvm(trainX,trainY,"ClassNames",[odorIdentities(1) odorIdentities(12)]);
sv = SVMModeltrained.SupportVectors;

% Visualize model results using first two neuron's responses
figure
gscatter(X(:,1),X(:,2),categorical(Y))
hold on
plot(sv(:,1),sv(:,2),'ko','MarkerSize',10)
legend(classOrder{1},classOrder{2},"Support Vector")
title({"AK014, 30 vCA1 units","Odor 1 versus Odor 12","SVM trained on first 11 trials"})
xlabel("response of neuron 1")
ylabel("response of neuron 2")
hold off

% Try visualizing instead using PCA
% Perform PCA on population responses
[PCAcoeff, score, latent, tsquared, explained, mu] = pca(trainX);
% Project the SVM results into the same PC space
svCentered = sv - mu; % Center support vectors using PCA mean
svPCA = svCentered * PCAcoeff; % Project centered support vectors into PCA space

% Visualize the model (using first 3 PC)
figure 
odorClasses = unique(trainY);
colors = lines(length(odorClasses));
for i = 1:length(odorClasses)
    idx = find(strcmp(trainY,odorClasses{i}));
    scatter3(score(idx,1), score(idx,2), score(idx,3), 60, colors(i,:),'filled')
    hold on
end
plot3(svPCA(:,1),svPCA(:,2),svPCA(:,3),'ko','MarkerSize',10)
%grid on
xlabel("PC 1")
ylabel("PC 2")
zlabel("PC 3")
title({"AK014, 30 vCA1 units","Odor 1 versus Odor 12","SVM trained on first 11 trials"})
legend(classOrder{1},classOrder{2},"Support Vector")
hold off

% Predict class for test data
predictedOdor = predict(SVMModeltrained,testX);
predictedCorrect = strcmp(predictedOdor,testY{1});

%% Now, build the model performing leave-one-out cross validation

% e.g. Use the first 11 trials as training data, leave out the last trial
% as the test data --> but do this for all (12C1) possible combinations

% Build the model
SVMModeltrainedLOOcrossValidated = fitcsvm(X,Y,"ClassNames",[odorIdentities(1) odorIdentities(12)],'CrossVal','on','Leaveout','on'); % feed in the full dataset
% Get information on SVM 
classOrder = SVMModeltrainedLOOcrossValidated.ClassNames;
% Use model to predict results
predictedOdors = kfoldPredict(SVMModeltrainedLOOcrossValidated);

figure
Yc = categorical(Y,classOrder,'Ordinal',true);
predictedOdorsc = categorical(predictedOdors,classOrder,'Ordinal',true);
cm = confusionchart(Yc,predictedOdorsc);
cm.Title = "Odorant Classification using AK014's 30 vCA1 units and LOOCV SVM approach";
cm.RowSummary = 'row-normalized';
cm.ColumnSummary = 'column-normalized';
cm

modelErrorRate = kfoldLoss(SVMModeltrainedLOOcrossValidated);
modelAccuracy = 1- modelErrorRate;

%% Now, build a model that allows for multi-class modeling (include all 12 odorants)

% For multiclass modeling -- try fitcecoc function
% Get feature matrix and class labels
Xnew = [];
Ynew = [];
classes = [];
for iOdor = 1:nOdors
    Xnew = [Xnew; squeeze(spikeCounts(iOdor,:,:))];
    Ynew = [Ynew repmat(string(odorIdentities{iOdor}),1,nTrialsPerOdor)];
    classes = [classes string(odorIdentities{iOdor})];
end

classesSortedbyFcnGrp = ["limonene" "cumene" "1-octanol" "eugenol" "hexanal" "valeraldehyde" "amyl acetate" "isoamyl acetate" "acetophenone" "valeric acid" "mineral oil" "air"];

% Note: MATLAB recommends against using Leave-One-Out Cross validation for
% multiclass SVMs. Because removal of a single point can drastically change
% the support vector in an SVM, this creates high variance between
% cross-validated models. K-fold cross validation is recommended instead.
% (Can even run the K-fold cross validation multiple times??)
% For a dataset size of N < 200, chatgpt recommends using 5-fold cross
% validation
% But other debate on the internet gives a less clear answer:
% See: https://stats.stackexchange.com/questions/154830/10-fold-cross-validation-vs-leave-one-out-cross-validation
% https://stats.stackexchange.com/questions/90902/why-is-leave-one-out-cross-validation-loocv-variance-about-the-mean-estimate-f/110537#110537
tic % For reference: Took 36 seconds to run on AK014 vCA1 (30 units)
multiClassModel = fitcecoc(Xnew, Ynew,"ClassNames",classesSortedbyFcnGrp,'CrossVal','on','Leaveout','on');
toc

% Get information on SVM 
classOrder = multiClassModel.ClassNames;
% Predict odors
predictedOdors = kfoldPredict(multiClassModel);

figure
Ynewc = categorical(Ynew,classOrder,'Ordinal',true);
predictedOdorsc = categorical(predictedOdors,classOrder,'Ordinal',true);
cm = confusionchart(Ynewc,predictedOdorsc);
cm.Title = "Odorant Classification using " + mouseLabel + "'s " + nUnitsThisRegion + " " + regionLabel + " units and LOOCV SVM approach";
cm.RowSummary = 'row-normalized';
cm.ColumnSummary = 'column-normalized';
cm

modelErrorRate = kfoldLoss(multiClassModel);
modelAccuracy = 1 - modelErrorRate;

saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_SVM_LOOCV_confusionmatrix" + ".png")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_SVM_LOOCV_confusionmatrix" + ".fig")

%% Now, lets build a bunch of models using repeatedly shuffled data as a null comparison

disp("Constructing null model using shuffled data...")
% Shuffle the odor labels
nRepeats = 750;
modelAccuracyNull = nan(1,nRepeats);
confusionMatrices = cell(1,nRepeats);
for iRepeat = 1:nRepeats

    disp("Calculating null model #" + iRepeat + "...")
    tic
    Yshuffled = Ynew(randperm(length(Ynew)));
    
    multiClassModelNull = fitcecoc(Xnew, Yshuffled,"ClassNames",classesSortedbyFcnGrp,'CrossVal','on','Leaveout','on');

    % Get information on SVM 
    classOrder = multiClassModelNull.ClassNames;
    % Predict odors
    predictedOdors = kfoldPredict(multiClassModelNull);

    % % Plot the confusion matrix
    % if iRepeat < 6
    %     figure
    %     Yshuffledc = categorical(Yshuffled,classOrder,'Ordinal',true);
    %     predictedOdorsc = categorical(predictedOdors,classOrder,'Ordinal',true);
    %     cm = confusionchart(Yshuffledc,predictedOdorsc);
    %     cm.Title = {"Odorant Classification using AK014's 30 vCA1 units and LOOCV SVM approach","Shuffled null #" + iRepeat};
    %     cm.RowSummary = 'row-normalized';
    %     cm.ColumnSummary = 'column-normalized';
    %     cm
    %     confusionMatrices{iRepeat} = cm;
    % end

    modelErrorRateNull = kfoldLoss(multiClassModelNull);
    modelAccuracyNull(1,iRepeat) = 1 - modelErrorRateNull;

    toc
end

tic
disp("Saving decoder data structure to .mat file.")
save(saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_SVM_LOOCV_Results.mat","mouseLabel","regionLabel","multiClassModel","Ynewc","predictedOdorsc","modelAccuracy","modelAccuracyNull", "odorIdentities",'-v7.3');
toc


%% Plot histogram of null accuracy values
chanceAccuracy = 1/nOdors;

pVal = 1 - sum(modelAccuracy > modelAccuracyNull)/length(modelAccuracyNull);

figure;
histogram(modelAccuracyNull,'Normalization','probability')
xlim([0 0.50])
xlabel("Model Accuracy (% correct)")
ylabel("Probability")
title({"Null SVM models built on shuffled data", mouseLabel + ", " + nUnitsThisRegion + " " + regionLabel + " units","# of Shuffles = " + nRepeats, "p = " + pVal})
xline(median(modelAccuracyNull),'g','LineWidth',0.5)
xline(mean(modelAccuracyNull),'m','LineWidth',0.5)
xline(chanceAccuracy,'b--','LineWidth',2)
xline(modelAccuracy,'r','LineWidth',2)
legend("null accuracy (shuffled)", ...
    "median null accuracy = " + median(modelAccuracyNull), ...
    "mean null accuracy = " + mean(modelAccuracyNull), ...
    "expected chance accuracy = " + chanceAccuracy, ...
    "actual accuracy (unshuffled) = " + modelAccuracy)

disp("Saving histogram of null and observed.")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_SVM_LOOCV_null_vs_observed_histogram" + ".png")
saveas(gcf, saveFigDir + "\" + mouseLabel + "_" + regionLabel + "_SVM_LOOCV_null_vs_observed_histogram" + ".fig")


%% Could also create a null model using before-odor presentation window (check accuracy value obtained using those values, not shuffled)

%% PART FOUR: Plot samples


%% PART FIVE: Feature extraction ???

%% PART SIX: Signal classification


%% PART SEVEN: Evaluate precision, recall, and F1 score