% plot_total_recorded_units_by_region.m - This code is designed to produce
% a bar graph of the total number of units recorded in specified regions
%
%   Inputs:
%       mouseLabel - standardized label that identifies a particular mouse
% 
%       [AK###]_spikes_grouped_by_odor_trial.mat - file containing population 
%       activity for all odorant trials for a single animal.
%           Dimension 1 - odorant #
%           Dimension 2 - trial #
%           Dimension 3 - unit #
%           Dimension 4 - binary spike (denoting presence(1)/absence(0) of 
%                           a spike at each sample points spanning the trial)
%           (Source: this data structure is automatically generated by the 
%           "align_sorted_spikes_to_odor_delivery.m" script.)
%
%   Outputs:
%       ...
%
%   Dependencies:
%       ...
%
% Designed by Anna C. Kolstad
% Author contact email: anna_kolstad@urmc.rochester.edu
% Padmanabhan Lab, University of Rochester School of Medicine
% PI contact email: krishnan_padmanabhan@urmc.rochester.edu
% Script first created: December 5, 2025 (Version 1.0)
% Script last updated: January 28, 2026
% Version 1.0. 



mice = ["AK012", "AK013", "AK014", "AK015", "AK024", "AK025", "AK026", "AK027"];
nMice = length(mice);
allUnitsAllMice = table;
    
[file, path] = uigetfile(".mat","Select unitLocationsAllMice.mat file.",baseDir);
load(fullfile(path,file),"unitLocationsAllMice"); 
nUnits = height(unitLocationsAllMice);
    
[file, path] = uigetfile(".mat","Select brainRegions.mat file.",baseDir);
load(fullfile(path,file),"brainRegions","nRegions"); 

brainRegionsCount = brainRegions;

% get unit count per region
for iRegion = 1:(nRegions+1)
    brainRegionsCount{4,iRegion} = sum(strcmp(unitLocationsAllMice.("anatomical location"), brainRegionsCount{3, iRegion}));
end

regionAbbrev = string(brainRegionsCount(3,:))';
regionCounts = cell2mat(brainRegionsCount(4,:))';
regionCountsTable = table(regionAbbrev,regionCounts,'VariableNames', {'Region','Count'});

% Remove regions with zero counts
regionCountsTable(regionCountsTable.Value == 0, :) = [];

piechart()